# Generated by Django 3.0.3 on 2020-05-27 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 27, 7, 54, 38, 712793, tzinfo=utc), verbose_name='发表时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
