# Generated by Django 3.0.3 on 2020-05-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200528_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='slug',
            field=models.CharField(max_length=256, verbose_name='栏目网址'),
        ),
    ]
